from pydantic import BaseModel, model_validator, Field
from typing import List, Optional, Literal
from enum import Enum

class IntentSchema(BaseModel):
    """Structured output from the intent parser."""
    location: str = Field(
        description="Fully resolved location (e.g. 'Austin, TX'). "
                    "Empty string if no location is mentioned."
    )
    topics: List[str] = Field(
        description="List of research topics inferred from the query. "
                    "Examples: ['weather'], ['news'], ['weather', 'outdoor_events'], "
                    "['traffic', 'road_conditions']. At least one topic required."
    )
    time_range: Literal["now", "today", "tonight", "this_week", "unspecified"] = Field(
        description="Temporal scope of the query."
    )
    is_ambiguous: bool = Field(
        description="True if the query is genuinely ambiguous — i.e., multiple "
                    "interpretations exist that would lead to different research plans."
    )
    ambiguity_reason: Optional[str] = Field(
        default=None,
        description="Required when is_ambiguous=True. One sentence explaining "
                    "the specific ambiguity."
    )

    @model_validator(mode="after")
    def ambiguity_requires_reason(self) -> "IntentSchema":
        if self.is_ambiguous and not self.ambiguity_reason:
            raise ValueError("ambiguity_reason is required when is_ambiguous=True")
        if not self.is_ambiguous and self.ambiguity_reason:
            self.ambiguity_reason = None  # clean up
        return self

    @model_validator(mode="after")
    def topics_not_empty(self) -> "IntentSchema":
        if not self.topics:
            raise ValueError("topics must contain at least one item")
        return self


class ClarificationSchema(BaseModel):
    """One targeted clarifying question for an ambiguous query."""
    question: str = Field(
        description="A single, specific question that resolves the detected ambiguity. "
                    "Must not ask multiple questions. Must be answerable in one sentence."
    )
    resolves_ambiguity: str = Field(
        description="Explains what the answer to this question will disambiguate."
    )


class PlanStep(BaseModel):
    """A single step in the LLM-generated research plan."""
    step_id: str = Field(
        description="Unique identifier, e.g. 'step_1', 'step_2'."
    )
    tool: Literal["weather_search", "news_search", "web_search"] = Field(
        description="Which tool to invoke for this step."
    )
    query: str = Field(
        description="The search query to pass to the tool."
    )
    location: str = Field(
        description="Location context for the search. Empty string if not applicable."
    )
    rationale: str = Field(
        description="Why this step is necessary given the user's query."
    )


class ResearchPlan(BaseModel):
    """The full research plan generated by the Planner."""
    steps: List[PlanStep] = Field(
        description="Ordered list of research steps. Must have at least one step."
    )
    current_step_idx: int = Field(
        default=0,
        description="Index into steps. Managed by the executor, not the LLM."
    )

    @model_validator(mode="after")
    def steps_not_empty(self) -> "ResearchPlan":
        if not self.steps:
            raise ValueError("Research plan must contain at least one step")
        return self

    def current_step(self) -> Optional[PlanStep]:
        if self.current_step_idx < len(self.steps):
            return self.steps[self.current_step_idx]
        return None

    def is_complete(self) -> bool:
        return self.current_step_idx >= len(self.steps)

    def advance(self) -> None:
        self.current_step_idx += 1

    def append_step(self, step: PlanStep) -> None:
        self.steps.append(step)


class EvidenceQuality(str, Enum):
    low = "low"
    medium = "medium"
    high = "high"


class CredibilityAnnotation(BaseModel):
    source: str
    authority_score: float = Field(ge=0.0, le=1.0)
    recency_score: float = Field(ge=0.0, le=1.0)
    relevance_score: float = Field(ge=0.0, le=1.0)
    contradicts_step_ids: List[str] = Field(default_factory=list)
    notes: Optional[str] = None


class StepResult(BaseModel):
    """Result from executing one research plan step."""
    step_id: str
    tool: str
    raw_data: str
    confidence: float = Field(ge=0.0, le=1.0)
    evidence_quality: EvidenceQuality
    gaps: List[str] = Field(
        default_factory=list,
        description="Specific information gaps the LLM identified in this result."
    )
    credibility: Optional[List[CredibilityAnnotation]] = None


class UncertaintyAction(str, Enum):
    accept = "accept"       # Proceed to next step
    retry  = "retry"        # Re-execute current step with amended query
    escalate = "escalate"   # Ask user a clarifying question


class UncertaintyDecision(BaseModel):
    """Decision made by the meta-routing agent after each step."""
    action: UncertaintyAction
    amended_query: Optional[str] = Field(
        default=None,
        description="Required when action=retry. The revised search query."
    )
    escalation_question: Optional[str] = Field(
        default=None,
        description="Required when action=escalate."
    )
    reasoning: str = Field(
        description="One sentence explaining the decision."
    )

    @model_validator(mode="after")
    def validate_action_fields(self) -> "UncertaintyDecision":
        if self.action == UncertaintyAction.retry and not self.amended_query:
            raise ValueError("amended_query required when action=retry")
        if self.action == UncertaintyAction.escalate and not self.escalation_question:
            raise ValueError("escalation_question required when action=escalate")
        return self


class SignalType(str, Enum):
    amend_plan   = "amend_plan"    # Requesting a new step be added
    flag_finding = "flag_finding"  # Surfacing a discovery for other agents
    warn         = "warn"          # Warning about data quality issue


class AgentSignal(BaseModel):
    """A signal posted to the shared scratchpad by an agent."""
    from_agent: str
    to_agent: Literal["controller", "any", "weather_agent", "news_agent", "planner"]
    signal_type: SignalType
    payload: str = Field(
        description="Free-text content of the signal. For amend_plan, "
                    "describe what step to add and why."
    )
    acted_on: bool = False


class DebateArgument(BaseModel):
    """An argument produced by Optimist or Skeptic sub-agents."""
    position: Literal["optimist", "skeptic"]
    claim: str = Field(description="The main claim being argued.")
    evidence_cited: List[str] = Field(
        description="List of step_ids referenced as evidence."
    )
    counterpoint_to: Optional[str] = Field(
        default=None,
        description="If this argument responds to the other side, reference their claim."
    )
    confidence_in_claim: float = Field(ge=0.0, le=1.0)


class JudgeVerdict(BaseModel):
    """Final calibrated answer from the Judge agent."""
    answer: str = Field(
        description="The complete, user-facing answer. Markdown allowed."
    )
    confidence: float = Field(
        ge=0.0, le=1.0,
        description="Judge's calibrated confidence in the answer."
    )
    uncertainty_flags: List[str] = Field(
        default_factory=list,
        description="Specific claims in the answer the user should treat with caution."
    )
    recommended_followup: Optional[str] = Field(
        default=None,
        description="One follow-up action the user could take to resolve remaining uncertainty."
    )
    winning_position: Literal["optimist", "skeptic", "split"] = Field(
        description="Which debate position was better-supported by evidence."
    )


class ClarificationState(BaseModel):
    """Tracks the state of a clarifying question exchange."""
    question: str
    awaiting_response: bool = True
    user_answer: Optional[str] = None


class AugmentStep(BaseModel):
    tool: Literal["weather_search", "news_search", "web_search"]
    query: str
    location: str
    rationale: str

class EvidenceSufficiencyDecision(BaseModel):
    decision: Literal["proceed", "augment", "proceed_with_caveats"]
    coverage_gaps: List[str] = Field(
        default_factory=list,
        description="Topics from the original query not adequately covered."
    )
    contradiction_summary: Optional[str] = Field(
        default=None,
        description="Summary of detected contradictions, if any."
    )
    augmentation_steps: List[AugmentStep] = Field(
        default_factory=list,
        description="Required when decision=augment. Max 2 steps."
    )
    overall_confidence: float = Field(ge=0.0, le=1.0)

    @model_validator(mode="after")
    def validate_augment(self) -> "EvidenceSufficiencyDecision":
        if self.decision == "augment" and not self.augmentation_steps:
            raise ValueError("augmentation_steps required when decision=augment")
        if len(self.augmentation_steps) > 2:
            raise ValueError("Maximum 2 augmentation steps")
        return self
